unit office365_integration;

{
  // REF:
  https://dev.outlook.com/Connectors/GetStarted

  // USAGE:
  with To365GroupIntegration.Create do
  begin
    URL:= 'https://outlook.office365.com/webhook/..........';

    Title := 'This is Title';
    Text:= 'This webhoot generated by [fastplaz](http://www.fastplaz.com) o365 integration';
    ThemeColor:= 'EA4300';
    respon := Send;

    Free;
  end;

  // CUSTOM:
  respon := CustomSend( '{"title":"This is title","text": "silahkan klik [cari](http://google.com) di sini....", "themeColor":"EA4300"}');


}

{$mode objfpc}{$H+}
{ $ include ../../define.inc}

interface

uses
  http_lib,
  Classes, SysUtils;

type

  { To365GroupIntegration }

  To365GroupIntegration = class(TInterfacedObject)
  private
    FIsSuccessfull: boolean;
    FText: string;
    FThemeColor: string;
    FTitle: string;
    FURL: string;
  public
    constructor Create;
    function CustomSend(JsonMessage: string = ''): IHTTPResponse;
    function Send: IHTTPResponse;
  published
    property URL: string read FURL write FURL;
    property Title: string read FTitle write FTitle;
    property Text: string read FText write FText;
    property ThemeColor: string read FThemeColor write FThemeColor;
    property IsSuccessfull: boolean read FIsSuccessfull;
  end;

implementation

{ To365GroupIntegration }

constructor To365GroupIntegration.Create;
begin
  FIsSuccessfull := False;
  FThemeColor := '';

end;

function To365GroupIntegration.CustomSend(JsonMessage: string): IHTTPResponse;
begin
  FIsSuccessfull := False;
  with THTTPLib.Create(URL) do
  begin
    ContentType := 'application/json';

    RequestBody := TStringStream.Create(JsonMessage);

    Result := Post;
    FIsSuccessfull := IsSuccessfull;
    Free;
  end;
end;

function To365GroupIntegration.Send: IHTTPResponse;
var
  s: string;
begin
  FIsSuccessfull := False;
  with THTTPLib.Create(URL) do
  begin
    ContentType := 'application/json';

    s := '{"title":"' + FTitle + '","text": "' + FText + '", "themeColor":"' + FThemeColor + '"}';
    RequestBody := TStringStream.Create(s);

    Result := Post;
    FIsSuccessfull := IsSuccessfull;
    Free;
  end;

end;



end.

