name: Update Logger (Development)

on:
  push:
    branches:
      - development

jobs:
  generate_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
          echo "$d" > LAST_UPDATED_DEVELOPMENT

      - name: Commit & push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add LAST_UPDATED_DEVELOPMENT
          git commit -m "[Github Actions]: Modify last update" || exit 0
          git push
